MCLinker=MCLinker
TESTLDFLAGS=-lm
all:
	clang++ -emit-llvm -S ./func.cpp -I. -o func.ll -ccc-host-triple arm-none-linux-gnueabi
	${MCLinker} ./test3.o -t ${TESTLDFLAGS} -relocation-model=pic -filetype=dso -march=arm ./test2.o -o ./func.so -dB ./func.ll ./test.o > result.correct
#	${MCLinker} -t ${TESTLDFLAGS} -relocation-model=pic -filetype=dso -march=arm -o ./func.so > result
#	${MCLinker} -relocation-model=pic -filetype=exe -march=arm ./func.ll -o ./func.exe
#	${MCLinker} -relocation-model=pic -filetype=arc -march=arm ./func.ll -o ./func.a
