DIAG(unsupported_exception, DiagnosticEngine::Warning, "Exception handling has not been fully supported yet.\nsection `%0'.", "Exception handling has not been fully supported yet.\nsection `%0'.")
DIAG(unsupported_symbolic_versioning, DiagnosticEngine::Warning, "Symbolic versioning has not been fully supported yet.\nsection `%0'.", "Symbolic versioning has not been fully supported yet.\nsection `%0'")
DIAG(unsupported_section, DiagnosticEngine::Error, "Unsupported section of `%0', kind: %1", "Unsupported section of `%0', kind: %1")
