//===- Linker.h -----------------------------------------------------------===//
//
//                     The MCLinker Project
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
#ifndef ALONE_SUPPORT_LINKER_CONFIG_H
#define ALONE_SUPPORT_LINKER_CONFIG_H

#include <string>

#include <mcld/Support/TargetRegistry.h>

namespace alone {

class LinkerConfig {
private:
  //===----------------------------------------------------------------------===//
  // Available Configurations
  //===----------------------------------------------------------------------===//
  std::string mTriple;

private:
  //===----------------------------------------------------------------------===//
  // These are generated by LinkerConfig furing initialize().
  //===----------------------------------------------------------------------===//
  const mcld::Target *mTarget;
  bool initializeTarget();

public:
  //===----------------------------------------------------------------------===//
  // Getters
  //===----------------------------------------------------------------------===//
  inline const std::string &getTriple() const
  { return mTriple; }

  inline const mcld::Target *getTarget() const
  { return mTarget; }

public:
  LinkerConfig(const std::string& pTriple);

  virtual ~LinkerConfig() { }
};

} // end namespace alone

#endif // ALONE_SUPPORT_LINKER_CONFIG_H
