#!/bin/bash
#                     The MCLinker project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.

function gettop() 
{
	local TOPFILE=tools/ld.mcld/main.cpp
	if [ -n "${MCLINKERTOP}" -a -f "${MCLINKERTOP}/${TOPFILE}" ]; then
		echo ${MCLINKERTOP}
	else
		if [ -f "${TOPFILE}" ]; then
			echo `pwd`;
		else
			local HERE=$PWD
			T=
			while [ \( ! \( -f $TOPFILE \) \) -a \( $PWD != "/" \) ]; do
				cd .. > /dev/null
				T=`PWD= pwd`
			done
			cd $HERE > /dev/null
			if [ -f "${T}/${TOPFILE}" ]; then
				echo ${T}
			fi
		fi
	fi
	
}

MCLINKERTOP=$(gettop)

# chdir to ${LIB}/Script
cd ${MCLINKERTOP}/lib/Script

# generate ScriptParser
/bin/bash ${MCLINKERTOP}/scripts/ylwrap `test -f "ScriptParser.yy" || echo 'ScriptParser.yy not found!'`ScriptParser.yy y.tab.c ScriptParser.cc y.tab.h ScriptParser.h y.output ScriptParser.output -- bison -o y.tab.c -d

# generate ScriptScanner
/bin/bash ${MCLINKERTOP}/scripts/ylwrap `test -f "ScriptScanner.ll" || echo 'ScriptScanner.ll no found!'`ScriptScanner.ll lex.yy.c ScriptScanner.cc -- flex -olex.yy.c

# update headers
HEADER_1="\/\/===- Auto generated by scripts\/genscriptparser.sh. Do not touch! --------===\/\/\n"
HEADER_2="\/\/\n"
HEADER_3="\/\/                     The MCLinker Project\n"
HEADER_4="\/\/\n"
HEADER_5="\/\/ This file is distributed under the University of Illinois Open Source\n"
HEADER_6="\/\/ License. See LICENSE.TXT for details.\n"
HEADER_7="\/\/\n"
HEADER_8="\/\/===----------------------------------------------------------------------===\/\/\n\n"

for parser_files in ScriptParser.h ScriptParser.cc stack.hh location.hh position.hh ScriptScanner.cc
do
	sed -i -e "1s/^/${HEADER_1}/" ${parser_files}
	sed -i -e "2s/^/${HEADER_2}/" ${parser_files}
	sed -i -e "3s/^/${HEADER_3}/" ${parser_files}
	sed -i -e "4s/^/${HEADER_4}/" ${parser_files}
	sed -i -e "5s/^/${HEADER_5}/" ${parser_files}
	sed -i -e "6s/^/${HEADER_6}/" ${parser_files}
	sed -i -e "7s/^/${HEADER_7}/" ${parser_files}
	sed -i -e "8s/^/${HEADER_8}/" ${parser_files}
done
